// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdminUsersController from "./admin_users_controller"
application.register("admin-users", AdminUsersController)

import AdminUsersFilterController from "./admin_users_filter_controller"
application.register("admin-users-filter", AdminUsersFilterController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import AnalyticsFiltersController from "./analytics_filters_controller"
application.register("analytics-filters", AnalyticsFiltersController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)

import BranchTemplateSelectorController from "./branch_template_selector_controller"
application.register("branch-template-selector", BranchTemplateSelectorController)

import CanvasZoomController from "./canvas_zoom_controller"
application.register("canvas-zoom", CanvasZoomController)

import CheckboxHiddenController from "./checkbox_hidden_controller"
application.register("checkbox-hidden", CheckboxHiddenController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CollapsibleStepController from "./collapsible_step_controller"
application.register("collapsible-step", CollapsibleStepController)

import ConditionPresetController from "./condition_preset_controller"
application.register("condition-preset", ConditionPresetController)

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ErrorHighlightController from "./error_highlight_controller"
application.register("error-highlight", ErrorHighlightController)

import FileAttachmentController from "./file_attachment_controller"
application.register("file-attachment", FileAttachmentController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import FloatingStepAdderController from "./floating_step_adder_controller"
application.register("floating-step-adder", FloatingStepAdderController)

import FlowPreviewController from "./flow_preview_controller"
application.register("flow-preview", FlowPreviewController)

import FolderAccordionController from "./folder_accordion_controller"
application.register("folder-accordion", FolderAccordionController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import GroupSelectorController from "./group_selector_controller"
application.register("group-selector", GroupSelectorController)

import GroupTreeController from "./group_tree_controller"
application.register("group-tree", GroupTreeController)

import ImageLightboxController from "./image_lightbox_controller"
application.register("image-lightbox", ImageLightboxController)

import InlineStepCreatorController from "./inline_step_creator_controller"
application.register("inline-step-creator", InlineStepCreatorController)

import InstructionTemplateController from "./instruction_template_controller"
application.register("instruction-template", InstructionTemplateController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ModalTriggerController from "./modal_trigger_controller"
application.register("modal-trigger", ModalTriggerController)

import MoveToFolderController from "./move_to_folder_controller"
application.register("move-to-folder", MoveToFolderController)

import MultiBranchController from "./multi_branch_controller"
application.register("multi-branch", MultiBranchController)

import OutputFieldsController from "./output_fields_controller"
application.register("output-fields", OutputFieldsController)

import PasswordToggleController from "./password_toggle_controller"
application.register("password-toggle", PasswordToggleController)

import PreviewUpdaterController from "./preview_updater_controller"
application.register("preview-updater", PreviewUpdaterController)

import QuestionFormController from "./question_form_controller"
application.register("question-form", QuestionFormController)

import QuickActionController from "./quick_action_controller"
application.register("quick-action", QuickActionController)

import RuleBuilderController from "./rule_builder_controller"
application.register("rule-builder", RuleBuilderController)

import ScenarioResultsController from "./scenario_results_controller"
application.register("scenario-results", ScenarioResultsController)

import ScenarioStepController from "./scenario_step_controller"
application.register("scenario-step", ScenarioStepController)

import SearchableDropdownController from "./searchable_dropdown_controller"
application.register("searchable-dropdown", SearchableDropdownController)

import SelectionGroupController from "./selection_group_controller"
application.register("selection-group", SelectionGroupController)

import SortSelectController from "./sort_select_controller"
application.register("sort-select", SortSelectController)

import SortableFoldersController from "./sortable_folders_controller"
application.register("sortable-folders", SortableFoldersController)

import StepControlsController from "./step_controls_controller"
application.register("step-controls", StepControlsController)

import StepFormController from "./step_form_controller"
application.register("step-form", StepFormController)

import StepModalController from "./step_modal_controller"
application.register("step-modal", StepModalController)

import StepOutlineController from "./step_outline_controller"
application.register("step-outline", StepOutlineController)

import StepSelectorController from "./step_selector_controller"
application.register("step-selector", StepSelectorController)

import StepTemplateController from "./step_template_controller"
application.register("step-template", StepTemplateController)

import StepTransitionsController from "./step_transitions_controller"
application.register("step-transitions", StepTransitionsController)

import StepsController from "./steps_controller"
application.register("steps", StepsController)

import SubflowSelectorController from "./subflow_selector_controller"
application.register("subflow-selector", SubflowSelectorController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TemplateFlowPreviewController from "./template_flow_preview_controller"
application.register("template-flow-preview", TemplateFlowPreviewController)

import TemplatePreviewController from "./template_preview_controller"
application.register("template-preview", TemplatePreviewController)

import TransitionEditorController from "./transition_editor_controller"
application.register("transition-editor", TransitionEditorController)

import VariableAutocompleteController from "./variable_autocomplete_controller"
application.register("variable-autocomplete", VariableAutocompleteController)

import VeConnectionController from "./ve_connection_controller"
application.register("ve-connection", VeConnectionController)

import VeStepModalController from "./ve_step_modal_controller"
application.register("ve-step-modal", VeStepModalController)

import ViewModeToggleController from "./view_mode_toggle_controller"
application.register("view-mode-toggle", ViewModeToggleController)

import VisualConditionController from "./visual_condition_controller"
application.register("visual-condition", VisualConditionController)

import VisualEditorController from "./visual_editor_controller"
application.register("visual-editor", VisualEditorController)

import WizardFlowPreviewController from "./wizard_flow_preview_controller"
application.register("wizard-flow-preview", WizardFlowPreviewController)

import WizardNavigationController from "./wizard_navigation_controller"
application.register("wizard-navigation", WizardNavigationController)

import WizardStep1ValidationController from "./wizard_step1_validation_controller"
application.register("wizard-step1-validation", WizardStep1ValidationController)

import WorkflowBuilderController from "./workflow_builder_controller"
application.register("workflow-builder", WorkflowBuilderController)

import WorkflowCollaborationController from "./workflow_collaboration_controller"
application.register("workflow-collaboration", WorkflowCollaborationController)

import WorkflowSearchController from "./workflow_search_controller"
application.register("workflow-search", WorkflowSearchController)

import WorkflowSidebarController from "./workflow_sidebar_controller"
application.register("workflow-sidebar", WorkflowSidebarController)
